name: Deploy
 
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: 'Build Website Image'
        run: |
          docker build . --tag ghcr.io/ivantomic77/portfolio-website:latest
          docker push ghcr.io/ivantomic77/portfolio-website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/apps/VuePortfolioSite
          docker-compose down --volumes --rmi all
          git pull
          git status
          docker-compose up -d
